# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. 
on:
  push:
    branches:
      - stylix58-rewrite
  pull_request:
    branches:
      - stylix58-rewrite
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: npm run build
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.2.0
        with:
          author_name: Fosscord

          # The email of the user that will be displayed as the author of the commit
          # Default: depends on the default_author input
          author_email: build@fosscord.com
          message: 'Build Landingpage'
